call plug#begin('~/.config/plugged')
Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
call plug#end()


syntax enable
colorscheme gruvbox
set background=dark
set encoding=utf-8
set nowrap
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab
set smartindent
set autoindent
set number
set showcmd
set wildmenu
set showmatch
set incsearch
set hlsearch
set laststatus=2
set noshowmode
set spelllang=en

set pyxversion=3

set nocompatible
filetype plugin on

let g:mapleader="\<Space>"
map <C-n> :NERDTreeToggle<CR>

" Window Navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Window Resize
nnoremap <M-h> :resize -2<CR>
nnoremap <M-j> :resize +2<CR>
nnoremap <M-k> :vertical resize -2<CR>
nnoremap <M-l> :vertical resize +2<CR>

" TAB & SHIFT-TAB to change buffer
nnoremap <TAB>   :bnext<CR>
nnoremap <S-TAB> :bprevious<CR>


